# Generated by Django 5.1.5 on 2025-02-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='image',
            field=models.ImageField(upload_to='content_images/'),
        ),
    ]
